modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "liquidrest"
version = "0.4.1b-1.18.2"
displayName = "LiquidREST"
updateJSONURL = "https://raw.githubusercontent.com/justmammt/LiquidREST-Forge/master/update.json"
displayURL = "https://liquidrest.fanilla.cloud/"
logoFile = "LIQUIDREST.png"
credits = "my mom"
authors = "justmammt"
description = '''
Server-side only Multi-threaded Forge Information API

LiquidREST is a simple http server that runs in parallels to the Server thread, it returns/modifies informations about players/worlds/environment
'''

[[dependencies.liquidrest]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "SERVER"
[[dependencies.liquidrest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
